- CHANGELOG.md
- README.md
- src/OdfAttributeName.ts
- src/OdfElementName.ts
- src/text/HyperLink.ts
- src/text/Paragraph.ts
- src/text/Text.ts
- test/integration.spec.ts
- test/text/Heading.spec.ts
- test/text/Paragraph.spec.ts
paragraph: append hyperlink
Append a hyperlink to a paragraph. It is possible to edit the text and URI of the hyperlink. If the hyperlink is empty it will be omitted in the final document.
Changes to the internal handling of text content were necessary for the paragraph to make this possible. Text now is handled as `Text` elements instead of a single instance variable.
Added changelog for v0.2.0 as it was missing.
Fixes #5
> Add text as a hyperlink

- CHANGELOG.md
- src/OdfElement.ts
- src/TextDocument.ts
- src/index.ts
- src/style/Style.ts
- src/text/Heading.ts
- src/text/HyperLink.ts
- src/text/List.ts
- src/text/ListItem.ts
- src/text/OdfTextElement.ts
- src/text/Paragraph.ts
- test/TextDocument.spec.ts
- test/integration.spec.ts
- test/style/Style.spec.ts
- test/text/Heading.spec.ts
- test/text/Hyperlink.spec.ts
- test/text/List.spec.ts
- test/text/Paragraph.spec.ts
general: rewrite of the public API
The public API (class names and methods) was reworked in order to use the terminology of the [Open Document Format](http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html).
Styles cannot be set directly on a paragraph any longer but on the `Style` that is bound to a paragraph.
> Rewrite the public API

- CHANGELOG.md
- src/OdfElementName.ts
- src/text/OdfTextElement.ts
- test/text/Paragraph.spec.ts
paragraph: Replace tabs and spaces with respective elements
Replace tab characters in paragraphs with tab elements.
Replace sequence of space characters in paragraphs with space element.
Fixes #10
> Respect tab and sequence of space characters

- .travis.yml
- README.md
For tests and npm publishing.
Secure variables `NPM_EMAIL` and `NPM_TOKEN` would have to be created in TravisCI interface.
closes #17
> Enable TravisCI 

- CHANGELOG.md
- src/text/OdfTextElement.ts
- test/text/Paragraph.spec.ts
paragraph: Ignore carriage return character in text
If a text contains a carriage return character, the character is ignored and not added to the final document.
Fixes: #15
> Text breaks if \r\n is entered as text of a paragraph

- .npmignore
- CHANGELOG.md
- src/index.ts
paragraph: Add image, tabstop, tabstoptype to default export
Export the `Image`, `TabStop` and `TabStopType` classes from the `index.ts`.
Additionally the .github folder, which contains the issue templates, was added to the .npmignore.
Fixes: #24
> Types for Image, TabStop and TabStopType are not exported

- CHANGELOG.md
- README.md
- src/draw/Image.ts
- src/index.ts
- src/style/IImageStyle.ts
- src/style/ImageStyle.ts
- test/draw/Image.spec.ts
- test/integration.spec.ts
- test/style/ImageStyle.spec.ts
image: Set image size on the image style
Fixes #41
> Move size configuration of an image to the image style

- CHANGELOG.md
- src/TextDocument.ts
- src/draw/Image.ts
- src/style/StyleHelper.ts
- src/text/HyperLink.ts
- src/text/Paragraph.ts
- test/TextDocument.spec.ts
- test/draw/Image.spec.ts
- test/text/Heading.spec.ts
- test/text/Hyperlink.spec.ts
- test/text/Paragraph.spec.ts
document: declare all XML namespaces in the document upfront instead of declaring them dynamically on usage.
Fixes #30
> Declare all XML namespaces on creation of the text document

- CHANGELOG.md
- docs/API.md
- src/style/IParagraphProperties.ts
- src/style/ParagraphProperties.spec.ts
- src/style/TabStop.spec.ts
- src/style/TabStop.ts
- test/integration.spec.ts
BREAKING CHANGE: The position of tab stops is now regarded as being given in millimeters instead of centimeters.
> refactor: always use millimeter as unit, except for font sizes

- CHANGELOG.md
- README.md
- package.json
- src/api/meta/Meta.ts
- src/api/office/FontFaceDeclarations.spec.ts
- src/api/office/FontFaceDeclarations.ts
- src/api/office/TextDocument.spec.ts
- src/api/office/TextDocument.ts
- src/api/office/index.ts
- src/api/style/FontFace.spec.ts
- src/api/style/FontFace.ts
- src/api/style/FontFamilyGeneric.ts
- src/api/style/index.ts
- src/api/text/Hyperlink.ts
- src/index.ts
- src/xml/OdfTextElementWriter.ts
- src/xml/TextDocumentWriter.spec.ts
- src/xml/TextDocumentWriter.ts
- src/xml/office/FontFaceDeclarationsWriter.spec.ts
- src/xml/office/FontFaceDeclarationsWriter.ts
- test/integration.spec.ts
- tslint.json
feature
Fonts are declared directly on the `TextDocument`. But the document should not know anything about fonts.
A new class `FontFaceDeclarations` was added. The `TextDocument` holds an instance of this new class. New fonts can be created on the `FontFaceDeclarations` class.
```typescript
// old
const document = new TextDocument();
const fontFace = document.declareFont('FreeSans', 'FreeSans', FontPitch.Variable);
// new
const document = new TextDocument();
const fontFaceDeclarations = document.getFontFaceDeclarations();
const fontFace = fontFaceDeclarations.create('FreeSans', 'FreeSans', FontPitch.Variable);
```
The logic for creating the XML for the font …
> feat: extend font declaration

- CHANGELOG.md
- README.md
- src/api/office/AutomaticStyles.ts
- src/api/style/IParagraphProperties.ts
- src/api/style/PageBreak.ts
- src/api/style/ParagraphProperties.spec.ts
- src/api/style/ParagraphProperties.ts
- src/api/style/ParagraphStyle.ts
- src/api/style/index.ts
- src/index.ts
- src/xml/OdfAttributeName.ts
- src/xml/office/StylesWriter.spec.ts
- src/xml/office/StylesWriter.ts
- test/integration.spec.ts
feature
see #31 
The `setPageBreakBefore()` and `getPageBreakBefore()` methods have been replaced with `setPageBreak()` and `getPageBreak()`. These new methods use the `PageBreak` enum which allows to set the break before or after or disable the page break again.
yes
> feat: allow page break to be before or after a paragraph

- CHANGELOG.md
- src/api/style/IParagraphProperties.ts
- src/api/style/ParagraphProperties.spec.ts
- src/api/style/ParagraphProperties.ts
- src/api/style/ParagraphStyle.ts
- src/xml/OdfAttributeName.ts
- src/xml/office/StylesWriter.spec.ts
- src/xml/office/StylesWriter.ts
- test/integration.spec.ts
feature
If there is a headline followed by a paragraph and this paragraph does not fit on the same page, it will be placed on the next page while the headline remains on the previous page.
On a paragraph style the `keep-with-next` flag can be set to tell the paragraph not to break before the next paragraph.
no
> style: add keep-with-next flag

- CHANGELOG.md
- docs/Features.md
- src/api/office/AutomaticStyles.ts
- src/api/style/IParagraphProperties.ts
- src/api/style/ParagraphProperties.spec.ts
- src/api/style/ParagraphProperties.ts
- src/api/style/ParagraphStyle.ts
- src/api/style/TextProperties.spec.ts
- src/api/style/TextProperties.ts
- src/api/util/index.ts
- src/api/util/isNonNegativeNumber.ts
- src/api/util/isPercent.ts
- src/api/util/isPositiveLength.ts
- src/xml/OdfAttributeName.ts
- src/xml/office/StylesWriter.spec.ts
- src/xml/office/StylesWriter.ts
- test/integration.spec.ts
feature
On the paragraph style it is now possible to configure margins and text indentation.
See [fo:margin-bottom](http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#property-fo_margin-bottom), [fo:margin-left](http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#property-fo_margin-left), [fo:margin-right](http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#property-fo_margin-right), [fo:margin-top](http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#property-fo_margin-top), [fo:text-indent](http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#property-f …
> style: add margin settings to paragraph style

- CHANGELOG.md
- docs/Features.md
- src/api/office/AutomaticStyles.ts
- src/api/style/Border.ts
- src/api/style/BorderStyle.ts
- src/api/style/IParagraphProperties.ts
- src/api/style/ParagraphProperties.spec.ts
- src/api/style/ParagraphProperties.ts
- src/api/style/ParagraphStyle.ts
- src/api/style/index.ts
- src/index.ts
- src/xml/OdfAttributeName.ts
- src/xml/office/StylesWriter.spec.ts
- src/xml/office/StylesWriter.ts
- test/integration.spec.ts
feature
On the paragraph style it is now possible to configure the border using the new methods `setBorderBottom`, `setBorderLeft`, `setBorderRight`, `setBorderTop`, `setBorder`.
See [fo:border-bottom](http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#property-fo_border-bottom), [fo:border-left](http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#property-fo_border-left), [fo:border-right](http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#property-fo_border-right), [fo:border-top](http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#property-fo_border-top) in the OASIS …
> feat(style): add border settings to paragraph

- CHANGELOG.md
- src/api/office/AutomaticStyles.ts
- src/api/style/Border.ts
- src/xml/office/StylesWriter.spec.ts
- src/xml/office/StylesWriter.ts
bug fix
see #94 
Fixed as suggested in the issue #94
no
> fix(style): tab stop is added as child of style:style element

- CHANGELOG.md
- docs/API.md
- src/api/office/AutomaticStyles.ts
- src/api/style/TabStop.spec.ts
- src/api/style/TabStop.ts
- src/api/style/TabStopLeaderStyle.ts
- src/api/style/index.ts
- src/index.ts
- src/xml/OdfAttributeName.ts
- src/xml/office/StylesWriter.spec.ts
- src/xml/office/StylesWriter.ts
feature
On the paragraph style it is now possible to configure the alignment character for tab stops of type `Char` using the new method `setChar`. Additionally the leader style of a tab stop now can be configured with the new `setLeaderStyle` and `setLeaderColor` methods.
See [style:char](http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#attribute-style_char), [style:leader-color](http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#attribute-style_leader-color), [style:leader-style](http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#attribute-style_leader-style) in the OASIS Document Format. …
> feat(style): add tab stop character and leader settings to paragraph style

- CHANGELOG.md
- README.md
- examples/homer-resume/index.ts
- src/api/office/TextBody.ts
- src/api/text/List.spec.ts
- src/api/text/List.ts
- src/api/text/ListItem.spec.ts
- src/api/text/ListItem.ts
- src/xml/DomVisitor.spec.ts
- test/integration.spec.ts
Bug fix
see #67 
The `addListItem` method on a list no longer accepts a string and it doesn't automagically create a "hidden" paragraph. Instead an empty list item is being created. On the `ListItem` instance it is possible to add headings or paragraphs.
yes
> text content of a list item cannot be styled

- CHANGELOG.md
- src/api/text/ListItem.spec.ts
- src/api/text/ListItem.ts
- test/integration.spec.ts
feature
A `ListItem` accepts one or multiple headings and paragraphs but it is not possible to add a list for creating sublists.
It is possible to add a `List` to a `ListItem` via the new `addList` method.
no
> implement sublists

- .eslintrc.json
- CHANGELOG.md
- package-lock.json
- package.json
- tslint.json
`chore: Changes to the build process or auxiliary tools and libraries such as documentation generation`
TSLint is used for linting, #122 asks to move to regular ESLint with typescript-eslint configured
ESLint is now being used
Make sure that if you're using VSCode with the ESLint extension that you update your preferences so that it can parse your typescript files.
**File > Preferences > Settings** (JSON View)
```
"eslint.validate": [
"javascript",
"javascriptreact",
"typescript",
"typescriptreact"
]
```
no
> chore(lint): replace tslint with eslint (#122)

- .eslintrc.json
- .npmignore
- CHANGELOG.md
- examples/homer-resume/index.ts
- package-lock.json
- package.json
- src/api/meta/Meta.ts
- src/api/office/AutomaticStyles.spec.ts
- src/api/office/AutomaticStyles.ts
- src/api/style/FontFace.ts
- src/api/style/ParagraphProperties.ts
- src/api/style/ParagraphStyle.ts
- src/api/style/Style.ts
- src/api/style/TabStop.spec.ts
- src/api/text/Hyperlink.ts
- src/xml/DomVisitor.spec.ts
- src/xml/OdfTextElementWriter.ts
- src/xml/meta/MetaWriter.spec.ts
- src/xml/office/FontFaceDeclarationsWriter.spec.ts
- src/xml/office/StylesWriter.spec.ts
- src/xml/office/StylesWriter.ts
- test/integration.spec.ts
chore
#122 requested to use standard rules, but #123 just replaced tslint with eslint without using the proper rule set.
Use standard and standardx for linting now. Fix linting errors and remove tslint annotations.
no
> use standardx for linting, fix linting errors, remove tslint annotations

- .travis.yml
- CHANGELOG.md
- package-lock.json
chore
---
Node.js 12 has entered LTS stage on 2019-10-21.
It is added to the Travis configuration so the build runs against this version as well
no
> chore(travis): add Node.js v12 to Travis configuration

- .travis.yml
- CHANGELOG.md
- package-lock.json
- package.json
chore
-
The 8.x Maintenance LTS cycle for Node.js has expired on December 31, 2019.
It is removed from the Travis configuration and the types for Node.js are updated.
no
> chore: drop support for Node.js 8

- package-lock.json
- package.json
Bumps **xmldom** from 0.4.0 to 0.5.0. This update includes a **security fix**.
Bumps **y18n** from 4.0.0 to 4.0.1. This update includes a **security fix**.
Security update
no
> fix(deps): [security] bump xmldom and y18n

- src/api/style/ParagraphProperties.ts
- src/api/util/isNonNegativeNumber.ts
- src/api/util/isPercent.ts
- src/api/util/isPositiveLength.ts
Refactoring
The parameters of the utility functions `isNonNegativeNumber`, `isPercent` and `isPositiveLength` are typed as `any`.
Change the parameter type to be `unknown`.
no
> refactor: no any-typed parameters

- src/api/office/AutomaticStyles.ts
- src/api/style/ITextProperties.ts
- src/api/style/ParagraphStyle.ts
- src/api/style/TextProperties.spec.ts
- src/api/style/TextProperties.ts
- src/xml/office/StylesWriter.spec.ts
- src/xml/office/TextPropertiesVisitor.ts
- test/integration.spec.ts
Feature
Text cannot be styled to show an overlining.
Text can be styled to show an overlining including the line style as well as its color and width.
Note: not all combinations are supported by readers like LibreOffice.
no
> feat(style): implement text overline

- .eslintrc.json
- .github/workflows/integration.yml
- .github/workflows/release.yml
- package-lock.json
- package.json
- src/api/meta/Meta.spec.ts
- src/api/style/FontFace.spec.ts
- src/api/style/ParagraphStyle.ts
- src/api/style/Style.spec.ts
- src/api/text/Heading.spec.ts
- src/api/text/Hyperlink.spec.ts
Update of dependencies.
Update the workflows to use the latest actions.
Bump node.js to at least v14.17.
Bump eslint from 7.26.0 to 8.7.0.
Bump eslint-plugin-prettier from 3.3.1 to 4.0.0.
Bump @typescript-eslint from 4.22.1 to 5.10.0.
Bump semantic-release from 17.0.7 to 18.0.1.
Bump @semantic-release/changelog from 5.0.1 to 6.0.1.
Bump @semantic-release/git from 9.0.0 to 10.0.1.
Fix linting errors.
BREAKING CHANGE: Dropped support for Node.js versions less than v14.17
and v15 to upgrade dev dependencies to their latest versions.
yes
> fix(deps): upgrade node to resolve vulnerabilities

- package-lock.json
- package.json
Dependencies update
Jest is included in version 27.5.1
Jest is included in version 28.1.1
no
> chore(deps): bump jest from 27.5.1 to 28.1.1

- package-lock.json
- package.json
bump @types/node from 14.18.21 to 14.18.32
bump @typescript-eslint/eslint-plugin from 5.27.0 to 5.40.1 bump @typescript-eslint/parser from 5.27.0 to 5.40.1 bump eslint from 8.17.0 to 8.26.0
bump eslint-plugin-prettier from 4.0.0 to 4.2.1
bump semantic-release from 19.0.3 to 19.0.5
bump typescript from 4.7.3 to 4.8.4
> chore: bump dev dependencies
